<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>03-VerifyHealthProgram</name>
   <tag></tag>
   <elementGuidId>091f1842-2d2e-409e-888d-76bff22f4d41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#program</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='program']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a37faf23-615c-4f45-af46-6eee1b25bd45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>program</value>
      <webElementGuid>0c2445a4-7d88-4a08-a220-915a1fb8c017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medicaid</value>
      <webElementGuid>f6e52a8b-11ee-4be8-8e52-2c01f64a1e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;program&quot;)</value>
      <webElementGuid>7a89b4d2-5439-4502-8c24-2a1ea140af90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='program']</value>
      <webElementGuid>00deb21d-f120-48db-9590-0f15e6add518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='summary']/div/div/div[4]/div[2]/p</value>
      <webElementGuid>fcd99107-d448-4283-8c6d-28f978f84b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/p</value>
      <webElementGuid>cb408b4a-8fa3-4314-88ce-742d49c0199d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'program' and (text() = 'Medicaid' or . = 'Medicaid')]</value>
      <webElementGuid>4d66ad3a-5511-4f66-81e6-2c5a47038099</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
